name: CI
on:
  pull_request:
    branches:
      - '*'
jobs:
  lint-typecheck-build:
    name: Lint, Type Check, and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: bun install
      - name: Lint
        run: bun lint
      - name: Type check
        run: bun type-check
      - name: Build
        run: bun run build
